/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BarbersRouteImport } from './routes/barbers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIdRouteImport } from './routes/vendor.$id'
import { Route as ReviewsIdRouteImport } from './routes/reviews.$id'
import { Route as OrderTrackingRouteImport } from './routes/order.tracking'
import { Route as OrderPickupRouteImport } from './routes/order.pickup'
import { Route as OrderConfirmationRouteImport } from './routes/order.confirmation'
import { Route as ItemItemIdRouteImport } from './routes/item.$itemId'
import { Route as CanteenIdRouteImport } from './routes/canteen.$id'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BarbersRoute = BarbersRouteImport.update({
  id: '/barbers',
  path: '/barbers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIdRoute = VendorIdRouteImport.update({
  id: '/vendor/$id',
  path: '/vendor/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsIdRoute = ReviewsIdRouteImport.update({
  id: '/reviews/$id',
  path: '/reviews/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderTrackingRoute = OrderTrackingRouteImport.update({
  id: '/order/tracking',
  path: '/order/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderPickupRoute = OrderPickupRouteImport.update({
  id: '/order/pickup',
  path: '/order/pickup',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order/confirmation',
  path: '/order/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemItemIdRoute = ItemItemIdRouteImport.update({
  id: '/item/$itemId',
  path: '/item/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const CanteenIdRoute = CanteenIdRouteImport.update({
  id: '/canteen/$id',
  path: '/canteen/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRouteWithChildren
  '/barbers': typeof BarbersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/merchant': typeof MerchantRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/signin': typeof SigninRoute
  '/track': typeof TrackRoute
  '/auth/otp': typeof AuthOtpRoute
  '/canteen/$id': typeof CanteenIdRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/order/confirmation': typeof OrderConfirmationRoute
  '/order/pickup': typeof OrderPickupRoute
  '/order/tracking': typeof OrderTrackingRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/vendor/$id': typeof VendorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRouteWithChildren
  '/barbers': typeof BarbersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/merchant': typeof MerchantRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/signin': typeof SigninRoute
  '/track': typeof TrackRoute
  '/auth/otp': typeof AuthOtpRoute
  '/canteen/$id': typeof CanteenIdRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/order/confirmation': typeof OrderConfirmationRoute
  '/order/pickup': typeof OrderPickupRoute
  '/order/tracking': typeof OrderTrackingRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/vendor/$id': typeof VendorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRouteWithChildren
  '/barbers': typeof BarbersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/home': typeof HomeRoute
  '/merchant': typeof MerchantRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/rewards': typeof RewardsRoute
  '/signin': typeof SigninRoute
  '/track': typeof TrackRoute
  '/auth/otp': typeof AuthOtpRoute
  '/canteen/$id': typeof CanteenIdRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/order/confirmation': typeof OrderConfirmationRoute
  '/order/pickup': typeof OrderPickupRoute
  '/order/tracking': typeof OrderTrackingRoute
  '/reviews/$id': typeof ReviewsIdRoute
  '/vendor/$id': typeof VendorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/barbers'
    | '/cart'
    | '/checkout'
    | '/home'
    | '/merchant'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/rewards'
    | '/signin'
    | '/track'
    | '/auth/otp'
    | '/canteen/$id'
    | '/item/$itemId'
    | '/order/confirmation'
    | '/order/pickup'
    | '/order/tracking'
    | '/reviews/$id'
    | '/vendor/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/barbers'
    | '/cart'
    | '/checkout'
    | '/home'
    | '/merchant'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/rewards'
    | '/signin'
    | '/track'
    | '/auth/otp'
    | '/canteen/$id'
    | '/item/$itemId'
    | '/order/confirmation'
    | '/order/pickup'
    | '/order/tracking'
    | '/reviews/$id'
    | '/vendor/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/barbers'
    | '/cart'
    | '/checkout'
    | '/home'
    | '/merchant'
    | '/notifications'
    | '/orders'
    | '/profile'
    | '/rewards'
    | '/signin'
    | '/track'
    | '/auth/otp'
    | '/canteen/$id'
    | '/item/$itemId'
    | '/order/confirmation'
    | '/order/pickup'
    | '/order/tracking'
    | '/reviews/$id'
    | '/vendor/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRouteWithChildren
  BarbersRoute: typeof BarbersRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  HomeRoute: typeof HomeRoute
  MerchantRoute: typeof MerchantRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  RewardsRoute: typeof RewardsRoute
  SigninRoute: typeof SigninRoute
  TrackRoute: typeof TrackRoute
  CanteenIdRoute: typeof CanteenIdRoute
  ItemItemIdRoute: typeof ItemItemIdRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  OrderPickupRoute: typeof OrderPickupRoute
  OrderTrackingRoute: typeof OrderTrackingRoute
  ReviewsIdRoute: typeof ReviewsIdRoute
  VendorIdRoute: typeof VendorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barbers': {
      id: '/barbers'
      path: '/barbers'
      fullPath: '/barbers'
      preLoaderRoute: typeof BarbersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/$id': {
      id: '/vendor/$id'
      path: '/vendor/$id'
      fullPath: '/vendor/$id'
      preLoaderRoute: typeof VendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews/$id': {
      id: '/reviews/$id'
      path: '/reviews/$id'
      fullPath: '/reviews/$id'
      preLoaderRoute: typeof ReviewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/tracking': {
      id: '/order/tracking'
      path: '/order/tracking'
      fullPath: '/order/tracking'
      preLoaderRoute: typeof OrderTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/pickup': {
      id: '/order/pickup'
      path: '/order/pickup'
      fullPath: '/order/pickup'
      preLoaderRoute: typeof OrderPickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/confirmation': {
      id: '/order/confirmation'
      path: '/order/confirmation'
      fullPath: '/order/confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$itemId': {
      id: '/item/$itemId'
      path: '/item/$itemId'
      fullPath: '/item/$itemId'
      preLoaderRoute: typeof ItemItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canteen/$id': {
      id: '/canteen/$id'
      path: '/canteen/$id'
      fullPath: '/canteen/$id'
      preLoaderRoute: typeof CanteenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthOtpRoute: typeof AuthOtpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthOtpRoute: AuthOtpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRouteWithChildren,
  BarbersRoute: BarbersRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  HomeRoute: HomeRoute,
  MerchantRoute: MerchantRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  RewardsRoute: RewardsRoute,
  SigninRoute: SigninRoute,
  TrackRoute: TrackRoute,
  CanteenIdRoute: CanteenIdRoute,
  ItemItemIdRoute: ItemItemIdRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  OrderPickupRoute: OrderPickupRoute,
  OrderTrackingRoute: OrderTrackingRoute,
  ReviewsIdRoute: ReviewsIdRoute,
  VendorIdRoute: VendorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
